version: '3'
services:
  app:
    build: .
    container_name: website
    command: ['make', 'run']
    ports:
      - 8000:8000
    volumes:
      - ./static:/app/static
      - ./db.sqlite3:/app/db.sqlite3
    restart: unless-stopped

  redis:
    container_name: redis
    image: redis
    ports:
      - '6379:6379'
    entrypoint: redis-server --appendonly yes
    restart: always

  celery:
    build: .
    container_name: celery
    command: ['make', 'celery']
    environment:
      - REDIS_URL=redis://redis:6379
    restart: always

  celery-beat:
    build: .
    container_name: celery-beat
    command: ['make', 'celery-beat']
    environment:
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
    restart: always
