# Generated by Django 2.2.8 on 2019-12-07 19:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0011_auto_20190508_0153'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('autoria', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MonitorQuery',
        ),
        migrations.CreateModel(
            name='MonitorQuery',
            fields=[
                ('periodictask_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_celery_beat.PeriodicTask')),
                ('average_price', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitors', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('django_celery_beat.periodictask',),
        ),
    ]
