# Generated by Django 2.2.8 on 2019-12-09 11:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autoria', '0004_auto_20191209_1012'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(validators=[django.core.validators.MinLengthValidator(1900), django.core.validators.MaxLengthValidator(2050)])),
                ('title', models.CharField(max_length=250)),
                ('uri', models.CharField(max_length=250)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='autoria.TransportBrand')),
                ('model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='autoria.TransportModel')),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='autoria.MonitorQuery')),
            ],
        ),
        migrations.CreateModel(
            name='MonitorPriceChangeEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_price', models.IntegerField()),
                ('new_price', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('announced', models.BooleanField(default=True)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='autoria.MonitorResult')),
            ],
        ),
    ]
